name: Run Tests with Coverage
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Set up Python and install dependencies
        run: |
          uv venv
          uv sync --dev
      - name: Set Qt to offscreen mode
        run: echo "QT_QPA_PLATFORM=offscreen" >> $GITHUB_ENV
      - name: Run tests
        run: |
          uv run coverage run -m unittest discover -s tests
          uv run coverage report -m
