name: Build and Release Executables

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        shell: bash
        run: |
          export APP_NAME="pyroddier-${{ matrix.os }}-${{ github.ref_name }}"
          pyinstaller src/main.py \
            --noconfirm \
            --clean \
            --name "$APP_NAME" \
            --distpath dist/ \
            --add-data "icons:icons" \
            --windowed \
            --icon=icons/pyroddier_logo.png

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: "dist/pyroddier-${{ matrix.os }}-${{ github.ref_name }}*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
